In [16]:
import csv
import numpy as np

data = []

# 打开CSV文件
with open('data2.csv', 'r') as file:
    # 创建CSV读取器
    csv_reader = csv.reader(file, delimiter=',')

    # 逐行读取数据
    for row in csv_reader:
        row_data = []
        for element in row:
            # 去除中括号，并按空格分割字符串
            element_values = element.strip("[]").split()
            # 将每个值转换为浮点数
            element_data = [float(value) for value in element_values]
            row_data.append(element_data)
        data.append(row_data)

# 将数据转换为NumPy数组
data = np.array(data)

# 打印结果
print(data)

[[[27.]
  [ 4.]
  [19.]]

 [[15.]
  [18.]
  [21.]]

 [[19.]
  [12.]
  [27.]]

 [[22.]
  [32.]
  [12.]]

 [[26.]
  [31.]
  [18.]]

 [[14.]
  [13.]
  [20.]]

 [[17.]
  [ 4.]
  [ 5.]]

 [[25.]
  [22.]
  [29.]]

 [[10.]
  [25.]
  [ 9.]]

 [[10.]
  [28.]
  [ 5.]]

 [[13.]
  [ 6.]
  [20.]]

 [[25.]
  [20.]
  [29.]]

 [[28.]
  [17.]
  [22.]]

 [[13.]
  [12.]
  [ 9.]]

 [[ 4.]
  [18.]
  [ 5.]]

 [[31.]
  [32.]
  [29.]]

 [[31.]
  [29.]
  [19.]]

 [[30.]
  [31.]
  [21.]]

 [[17.]
  [24.]
  [ 5.]]

 [[22.]
  [18.]
  [30.]]

 [[10.]
  [26.]
  [ 6.]]

 [[14.]
  [13.]
  [29.]]

 [[ 6.]
  [30.]
  [ 4.]]

 [[ 3.]
  [23.]
  [22.]]

 [[15.]
  [14.]
  [ 4.]]

 [[ 9.]
  [25.]
  [18.]]

 [[26.]
  [32.]
  [20.]]

 [[22.]
  [29.]
  [ 5.]]

 [[ 5.]
  [14.]
  [ 8.]]

 [[19.]
  [ 4.]
  [25.]]

 [[ 9.]
  [14.]
  [29.]]

 [[25.]
  [27.]
  [28.]]

 [[30.]
  [13.]
  [ 6.]]

 [[24.]
  [ 3.]
  [24.]]

 [[31.]
  [23.]
  [15.]]

 [[ 7.]
  [17.]
  [13.]]

 [[20.]
  [ 7.]
  [27.]]

 [[14.]
  [24.]
  [21.]]

 [[25.]
  [1